/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myxenia.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractMyXeniaScopeProvider extends XbaseBatchScopeProvider {
}
