/*
 * generated by Xtext 2.25.0
 */
package org.xtext.myjess.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyJessAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/myjess/parser/antlr/internal/InternalMyJessParser.tokens");
	}
}
