/*
 * generated by Xtext 2.25.0
 */
package org.xtext.myjess.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.myjess.ui.internal.MyjessActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyJessExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MyjessActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MyjessActivator activator = MyjessActivator.getInstance();
		return activator != null ? activator.getInjector(MyjessActivator.ORG_XTEXT_MYJESS_MYJESS) : null;
	}

}
