/*
 * generated by Xtext 2.25.0
 */
package org.xtext.myjess.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.xtext.myjess.parser.antlr.internal.InternalMyJessParser;

public class MyJessTokenSource extends AbstractIndentationTokenSource {

	public MyJessTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalMyJessParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalMyJessParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalMyJessParser.RULE_END;
	}

}
