/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myxenia.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyXeniaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/myxenia/parser/antlr/internal/InternalMyXeniaParser.tokens");
	}
}
