/*
 * generated by Xtext 2.25.0
 */
package org.xtext.mycsm.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractMyCsmScopeProvider extends XbaseBatchScopeProvider {
}
