/*
 * generated by Xtext 2.25.0
 */
package org.xtext.myjess;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyJessStandaloneSetup extends MyJessStandaloneSetupGenerated {

	public static void doSetup() {
		new MyJessStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
