/*
 * generated by Xtext 2.25.0
 */
package org.xtext.mycsm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mycsm.MyCsmRuntimeModule;
import org.xtext.mycsm.MyCsmStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyCsmIdeSetup extends MyCsmStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyCsmRuntimeModule(), new MyCsmIdeModule()));
	}
	
}
