/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myxenia.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.myxenia.MyXeniaRuntimeModule;
import org.xtext.example.myxenia.MyXeniaStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyXeniaIdeSetup extends MyXeniaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyXeniaRuntimeModule(), new MyXeniaIdeModule()));
	}
	
}
