/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myxenia.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.myxenia.ui.internal.MyxeniaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyXeniaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MyxeniaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MyxeniaActivator activator = MyxeniaActivator.getInstance();
		return activator != null ? activator.getInjector(MyxeniaActivator.ORG_XTEXT_EXAMPLE_MYXENIA_MYXENIA) : null;
	}

}
