/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myxenia;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyXeniaStandaloneSetup extends MyXeniaStandaloneSetupGenerated {

	public static void doSetup() {
		new MyXeniaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
