/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myxenia.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyXeniaUiModule extends AbstractMyXeniaUiModule {

	public MyXeniaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
