/*
 * generated by Xtext 2.25.0
 */
package org.xtext.myjess.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyJessUiModule extends AbstractMyJessUiModule {

	public MyJessUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
