/*
 * generated by Xtext 2.25.0
 */
package org.xtext.demo.mydsl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractMyDslScopeProvider extends XbaseBatchScopeProvider {
}
