/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myxenia.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.myxenia.ui.internal.MyxeniaActivator;

public class MyXeniaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MyxeniaActivator.getInstance().getInjector("org.xtext.example.myxenia.MyXenia");
	}

}
