/*
 * generated by Xtext 2.25.0
 */
package org.xtext.myjess.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.myjess.MyJessRuntimeModule;
import org.xtext.myjess.MyJessStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyJessIdeSetup extends MyJessStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyJessRuntimeModule(), new MyJessIdeModule()));
	}
	
}
