/*
 * generated by Xtext 2.25.0
 */
package org.xtext.mycsm.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.xtext.mycsm.parser.antlr.internal.InternalMyCsmParser;

public class MyCsmTokenSource extends AbstractIndentationTokenSource {

	public MyCsmTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalMyCsmParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalMyCsmParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalMyCsmParser.RULE_END;
	}

}
